-- File: internal/persist/migrations/postgres/001_init.sql
CREATE TABLE accounts (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	username TEXT NOT NULL UNIQUE,
	pass_hash BYTEA NOT NULL,
	created_at BIGINT NOT NULL,
	last_login_at BIGINT
);

CREATE TABLE sessions (
	token TEXT PRIMARY KEY,
	user_id BIGINT NOT NULL,
	expires_at BIGINT NOT NULL,
	created_at BIGINT NOT NULL
);

CREATE TABLE army_loadouts (
	user_id BIGINT PRIMARY KEY,
	element_id INTEGER NOT NULL,
	army_ability_1 INTEGER NOT NULL DEFAULT 0,
	army_ability_2 INTEGER NOT NULL DEFAULT 0,
	army_ability_3 INTEGER NOT NULL DEFAULT 0,
	army_ability_4 INTEGER NOT NULL DEFAULT 0,
	ability_pawn INTEGER NOT NULL DEFAULT 0,
	ability_knight INTEGER NOT NULL DEFAULT 0,
	ability_bishop INTEGER NOT NULL DEFAULT 0,
	ability_rook INTEGER NOT NULL DEFAULT 0,
	ability_queen INTEGER NOT NULL DEFAULT 0,
	ability_king INTEGER NOT NULL DEFAULT 0,
	item_1 INTEGER NOT NULL DEFAULT 0,
	item_2 INTEGER NOT NULL DEFAULT 0,
	item_3 INTEGER NOT NULL DEFAULT 0,
	item_4 INTEGER NOT NULL DEFAULT 0,
	updated_at BIGINT NOT NULL
);

CREATE TABLE progression (
	user_id BIGINT PRIMARY KEY,
	level INTEGER NOT NULL,
	xp BIGINT NOT NULL
);

CREATE TABLE user_unlocks (
	user_id BIGINT NOT NULL,
	flag_id INTEGER NOT NULL,
	unlocked_at BIGINT NOT NULL,
	PRIMARY KEY (user_id, flag_id)
);
